; Secret of Mana (USA) - New-game intro VWF
; ============================================
; Reference for the 65816 code emitted by build_patch.py.
; Dynamic event/DTE data is generated by the Python builder.
;
; Current runtime layout:
;   intro VWF window  : $CA:0C02-$0E8A (exclusive end $0E8B)
;   relocated $0401-0F: $CA:FF70-$FFB7
;   private text buf  : $7E:9390-$93BB (44 bytes)
;   logical capacity  : 38 visible glyphs + one following control unit
;   VWF bitmap        : stock $7E:9000 tile-major 32 x 12-byte cells
;
; Hooks fall back to stock behavior outside event $0400.

hirom


!INTRO_START       = $0C02
!INTRO_END         = $0E8B      ; current generated build value
!PRIVATE_BUFFER    = $9390
!VWF_BITMAP        = $9000

!WIDTH_TABLE       = $C74440
!SHARED_ROW_RENDER  = $C74560

; Scratch WRAM
!COUNT              = $9380
!LINE_END_FLAG      = $9381
!PIXEL_CURSOR       = $9382
!GLYPH_ADVANCE      = $9385
!TEMP16_ROWS        = $9386      ; multiply scratch, then 12-row counter

; $9383/$9384/$9388/$9389 are owned transiently by the shared compositor.

; ---------------------------------------------------------------------------
; Stock hooks
; ---------------------------------------------------------------------------

org $C01664
    jml vwf_entry

; Shared private-buffer parser hooks. The executable canonical source is
; ../../shared/vwf_text_buffer.py; see ../../shared/vwf_text_buffer.asm.
org $C017CE
    jml shared_vwf_parser_write

org $C016B8
    jml shared_vwf_buffer_init

org $C018DE
    jml shared_vwf_previous_char

org $C016C6
    jsl shared_vwf_capacity
    nop #6

; Do not consume previous-row carry in the outline shift.
org $C0163D
    asl

; ---------------------------------------------------------------------------
; Intro-only VWF renderer
; ---------------------------------------------------------------------------

org $C74285

vwf_entry:
    lda.l $001D03
    cmp #$CA
    beq .check_pointer

.stock:
    lda $A1CE
    and #$7F
    jml $C01669

.check_pointer:
    rep #$20
    lda.l $001D01
    cmp #!INTRO_START
    bcc .stock16
    cmp #!INTRO_END
    bcs .stock16
    bra .intro

.stock16:
    sep #$20
    bra .stock

.intro:
    sep #$20

    ; Save decoded count and line-end flag.
    lda $A1CE
    and #$7F
    beq .stock
    sta !COUNT

    lda $A1CE
    and #$80
    sta !LINE_END_FLAG

    ; Clear the stock tile-major 32-cell x 12-row bitmap.
    ldx #$0000
.clear_bitmap:
    stz !VWF_BITMAP,x
    inx
    cpx #$0180
    bne .clear_bitmap

    stz !PIXEL_CURSOR
    ldx #$0000

.next_char:
    txa
    cmp !COUNT
    beq .done

    lda !PRIVATE_BUFFER,x
    inx
    phx

    ; Direct text codes are $80-based.
    rep #$20
    and #$00FF
    sec
    sbc #$0080
    tax
    sep #$20

    lda.l !WIDTH_TABLE,x
    sta !GLYPH_ADVANCE

    ; glyph_offset = glyph_index * 12
    rep #$20
    txa
    asl
    asl
    sta !TEMP16_ROWS
    asl
    clc
    adc !TEMP16_ROWS
    tax

    ; Compute the tile-major destination from the current pixel cursor.
    ; The shared compositor derives cursor&7 itself.
    rep #$20
    lda !PIXEL_CURSOR
    and #$00FF
    lsr
    lsr
    lsr
    asl
    asl
    sta !TEMP16_ROWS
    asl
    clc
    adc !TEMP16_ROWS
    tay

    sep #$20
    lda #$0C
    sta !TEMP16_ROWS

.row:
    jsl !SHARED_ROW_RENDER
    inx
    nop #8                  ; preserve runtime-validated code layout
    sta !VWF_BITMAP,y
    iny
    dec !TEMP16_ROWS
    bne .row

    plx
    lda !PIXEL_CURSOR
    clc
    adc !GLYPH_ADVANCE
    sta !PIXEL_CURSOR
    bra .next_char

.done:
    ; Stock event $0400 contains a WAIT in the middle of its final logical
    ; sentence. When the next opcode is WAIT, convert the VWF pixel cursor to
    ; an 8-pixel cell coordinate so resume-after-WAIT does not create a large
    ; fixed-width gap.
    rep #$20
    lda.l $001D01
    tax
    sep #$20
    lda.l $CA0000,x
    cmp #$28
    bne .return

    lda !PIXEL_CURSOR
    clc
    adc #$07
    lsr
    lsr
    lsr
    ora !LINE_END_FLAG
    sta $A1CE

.return:
    jml $C016B7

; ---------------------------------------------------------------------------
; Shared stock-font row renderer
; ---------------------------------------------------------------------------
;
; The 13-byte helper at $C7:4560 is emitted by
; ../../shared/vwf_row_renderer.py. It performs the stock font-row load, calls
; the shared framing selector, then calls the shared compositor. `vwf_dialogues`
; installs/calls the same bytes.

; ---------------------------------------------------------------------------
; Shared row compositor
; ---------------------------------------------------------------------------
;
; The byte-identical helper at $C7:4C90 is emitted by
; ../../shared/vwf_compositor.py; see ../../shared/vwf_compositor.asm. It owns
; only row shift/current-cell merge/right-side spill. The intro now reads the
; stock font directly; width lookup, cursor advance and event-specific behavior
; remain local.

; ---------------------------------------------------------------------------
; Shared runtime framing selector
; ---------------------------------------------------------------------------
;
; The selector bundle at $C7:44C0-$4557 is generated by
; ../../shared/vwf_framing.py from the same logic used by `vwf_dialogues`. It
; receives a stock row in A and its 12-byte stock-font offset in X, then returns
; the runtime-validated framed row without changing X or accumulator width.

; ---------------------------------------------------------------------------
; Shared private decoded-text buffer bridge
; ---------------------------------------------------------------------------
;
; `vwf_intro` and `vwf_dialogues` install the same parser hooks/helpers byte-for-byte.
; Their executable source is ../../shared/vwf_text_buffer.py and the readable
; 65816 reference is ../../shared/vwf_text_buffer.asm.
;
; `vwf_intro` writes its runtime config at $C7:4C80:
;   $05, then the validated exclusive intro runtime end pointer $0E8B.
; The shared initializer then selects parser mode 1 only for the real event-
; engine caller of $C0:16B8 (stacked return $114B), bank $CA, and pointers in
; $0C02..!INTRO_END. GAME SELECT's $235B caller remains stock.
;
; Mode 1 preserves the validated intro behavior exactly:
;   - decode to $7E:9390-$93BB;
;   - fixed capacity $27 = 38 glyphs + following control;
;   - previous-character reads come from the private buffer.
;
; Shared helper locations:
;   $C7:43D0  parser private/stock write
;   $C7:4AC0  caller-gated buffer initializer
;   $C7:4B40  previous-character source selector
;   $C7:4BC0  intro/dialogue/stock capacity selector
;   $C7:4C80  `vwf_intro` intro config

; ---------------------------------------------------------------------------
; Generated data (emitted by build_patch.py)
; ---------------------------------------------------------------------------
;
; $C7:4440-$44BF  128-byte glyph advance table
; $C7:44C0-$4557  shared runtime framing selector bundle
; $CA:FF70-$FFB7  relocated unchanged stock events $0401-$040F
;
; `french_intro` separately owns the French glyph installation, translated
; event `$0400`, layout metadata, `$E6` DTE threshold, loader and private DTE
; table. This source file intentionally documents only the VWF runtime side.
