; Secret of Mana (USA) — dialogue VWF continuous-cursor renderer
; Documentation/source-map reference; build_patch.py is the canonical emitter.
; =====================================================
;
; Runtime-validated event scope:
;   $C0:1664 is shared by the event engine, GAME SELECT and another caller.
;   At $C0:167D the generated entry helper reads the untouched JSR return
;   address at 1,S. Only return $1152 (call from $C0:1150) plus event bank
;   $C9/$CA activates component 06. GAME SELECT returns as $235E and stays stock.
;   Component 05 intercepts translated intro event $0400 earlier at $C0:1664,
;   so component 06 never reaches this entry during that intro.
;
; Runtime-validated renderer:
;   keep stock $C0:168A-$16B0 code -> glyph lookup/render path intact;
;   128-entry advance table at $ED:7200;
;   space=$80 => 4 px advance;
;   lowercase a-z => framed ink width + 1 px black separator;
;   uppercase/punctuation/French framing and metrics as documented in README.md;
;   continuous cumulative pixel cursor with cross-cell merge/spill;
;   generic interrupted-chunk conversion before stock progression.
;
; $7E:9385 is the per-invocation component-06 active tag. It overlaps the intro
; renderer's glyph-advance scratch only because the two renderers are mutually
; exclusive: component 05 exits before $C0:167D for event $0400.
;
; The post-outline repair at $C0:1168 remains deliberately $C9-only pending a
; separate runtime audit for $CA; the core renderer itself is caller-gated C9/CA.

hirom

!RENDER_ACTIVE = $9385

org $C01168
    jml dialogue_outline_post

org $C0167D
    jml dialogue_render_init

org $C01686
    jml dialogue_char_start

org $C016A4
    jsl dialogue_font_row

org $C016B1
    jml dialogue_char_end
    nop #2

org $ED7040
dialogue_render_init:
    ; Generated byte-exactly by build_patch.py.
    ; Clear !RENDER_ACTIVE first. Read return address at 1,S; accept only $1152
    ; (event-engine JSR $C0:1150 -> $1664), then require bank $C9 or $CA.
    ; For an accepted invocation save the decoded count, reset chunk/cursor
    ; state, clear the VWF bitmap, and replay the overwritten stock LDA/STA.

org $ED70C0
dialogue_char_end:
    ; If the invocation is tagged active, read the current character's advance
    ; from $ED:7200 and reproduce the stock DEC $A176 / loop contract. On the
    ; final slot continue at $ED:7340 for interrupted-chunk commit. Otherwise
    ; replay the stock loop tail. A remains 8-bit.

org $ED7100
dialogue_font_row:
    ; Replays LDA.l $D2DC00,X. For a tagged event-render invocation, compose the
    ; selected row at pixel_cursor&7 with cross-cell spill. Non-event callers
    ; return the untouched stock row.

org $ED7180
dialogue_char_start:
    ; For a tagged event-render invocation, snapshot physical chunk cells when
    ; X reaches the saved decoded count, derive
    ; Y = floor(pixel_cursor/8)*12, then replay the untouched stock glyph-
    ; addressing path at $C0:168A.

org $ED71B0
dialogue_framing_selector:
    ; a-h/k/m-s/u-z = 1 px, i/l = 3 px, j/t = 2 px.
    ; Rows after z branch to the adjacent punctuation selector.

org $ED71E8
dialogue_punctuation_framing_selector:
    ; Post-lowercase dispatch. The fixed JML trampoline remains exactly at
    ; $ED:71F4 and forwards A+ to the extended selector.

org $ED7200
dialogue_width_table:
    ; 128 generated advances for decoded codes $80-$FF.

org $ED7280
dialogue_outline_post:
    ; Entered at $C0:1168 after stock JSR $162C. Current generated helper repairs
    ; cross-cell outline boundaries only for bank $C9, then replays the stock
    ; state tail. This secondary repair has not yet been generalized to $CA.

org $ED72F0
dialogue_extended_framing_selector:
    ; A-H/J-Z shift 1 px, I shifts 3 px. Runtime-validated punctuation and
    ; French $D4-$E5 rules are preserved; $CD-$D3 stay untouched.

org $ED7340
dialogue_chunk_commit:
    ; For a tagged event-render invocation, non-line-break chunks replace
    ; $A1CE's decoded count with the physical-cell count captured from the
    ; actual cumulative VWF width. No event addresses/opcodes are tested.

org $ED7380
dialogue_chunk_cells_snapshot:
    ; When X equals the decoded count saved at renderer entry, convert the
    ; useful cursor to ceil(px/8). Also handles the full 32-slot / 256-pixel
    ; 8-bit cursor-wrap edge case.

org $ED73B0
dialogue_event_render_scope:
    ; Return C=1 iff !RENDER_ACTIVE is non-zero; internal hooks use this private
    ; tag instead of re-testing shared global state.
