; Secret of Mana (USA) — dialogue VWF continuous-cursor renderer
; Documentation/source-map reference; build_patch.py is the canonical emitter.
; =====================================================
;
; Runtime-validated event scope:
;   $C0:1664 is shared by the event engine, GAME SELECT and another caller.
;   At $C0:167D the generated entry helper reads the untouched JSR return
;   address at 1,S. Only return $1152 (call from $C0:1150) plus event bank
;   $C9/$CA activates component 06. GAME SELECT returns as $235E and stays stock.
;   Component 05 intercepts translated intro event $0400 earlier at $C0:1664,
;   so component 06 never reaches this entry during that intro.
;
; Renderer core remains the runtime-validated stock-glyph architecture:
;   keep stock $C0:168A-$16B0 glyph lookup/addressing code intact;
;   decoded bytes now come from the shared private $7E:9390-$93BB buffer;
;   tagged dialogue invocations render 38 logical slots instead of 32;
;   physical output remains the stock 32-cell / 256-pixel bitmap;
;   128-entry advance table at $ED:7200;
;   space=$80 => 4 px advance;
;   lowercase a-z => framed ink width + 1 px black separator;
;   uppercase/punctuation/French framing and metrics as documented in README.md;
;   continuous cumulative pixel cursor with cross-cell merge/spill;
;   generic interrupted-chunk conversion before stock progression.
;
; $7E:9385 is the per-invocation component-06 active tag. It overlaps the intro
; renderer's glyph-advance scratch only because the two renderers are mutually
; exclusive: component 05 exits before $C0:167D for event $0400.
;
; Runtime-validated post-outline scope: the repair at $C0:1168 gates on exact
; component-06 active tag $9385 == $01, covering ordinary C9/CA dialogue while
; excluding component 05 intro, where $9385 is a glyph advance in the validated
; 3..8 range.

hirom

; Shared parser hooks/helpers are emitted byte-identically by components 05
; and 06 from ../../shared/vwf_text_buffer.py. Component 06 writes marker $06
; at $C7:4C84, which enables mode 2 only for the event-engine parser caller
; ($C0:1149 -> $16B8, stacked return $114B) and banks $C9/$CA. GAME SELECT's
; parser caller ($235B) remains stock. See ../../shared/vwf_text_buffer.asm.
org $C016B8
    jml shared_vwf_buffer_init
org $C016C6
    jsl shared_vwf_capacity
    nop #6
org $C017CE
    jml shared_vwf_parser_write
org $C018DE
    jml shared_vwf_previous_char

org $C01168
    jml dialogue_outline_post

org $C0167D
    jml dialogue_render_init

org $C01686
    jml dialogue_char_start

org $C016A4
    jsl dialogue_font_row

org $C016B1
    jml dialogue_char_end
    nop #2

org $C016EA
    ; Generated build hooks the stock LDA $0000,Y / INY only for the
    ; dialogue parser preflight. Parser modes other than 2 replay stock.
    jml dialogue_parser_fetch

org $ED7040
dialogue_render_init:
    ; Generated byte-exactly by build_patch.py.
    ; Clear $9385 first. Read return address at 1,S; accept only $1152
    ; (event-engine JSR $C0:1150 -> $1664), then require bank $C9 or $CA.
    ; For an accepted invocation save the decoded count, reset chunk/cursor
    ; state, clear the VWF bitmap, set the renderer loop to 38 slots, and
    ; continue into the stock glyph-addressing path. Stock callers keep 32.

org $ED70C0
dialogue_char_end:
    ; If the invocation is tagged active, read the current character's advance
    ; from $ED:7200 and reproduce the stock DEC $A176 / loop contract. On the
    ; final slot continue at $ED:7340 for interrupted-chunk commit. Otherwise
    ; replay the stock loop tail. A remains 8-bit.

org $ED7100
dialogue_font_row:
    ; Test the validated renderer-active tag. Tagged dialogue calls delegate
    ; stock row load + shared framing + shared composition to $C7:4560.
    ; Non-event callers replay only LDA.l $D2DC00,X and return unchanged.

org $ED7180
dialogue_char_start:
    ; For a tagged event-render invocation, snapshot physical chunk cells when
    ; X reaches the saved decoded count, derive Y=floor(pixel_cursor/8)*12,
    ; load the decoded byte from $9390,X, then enter the untouched stock glyph
    ; normalization/addressing code at $C0:168A. Non-event callers load A1A4,X.

org $ED7200
dialogue_width_table:
    ; 128 generated advances for decoded codes $80-$FF.

org $ED7280
dialogue_outline_post:
    ; Entered at $C0:1168 after stock JSR $162C. Runtime-validated scope tests
    ; exact component-06 active tag $9385 == $01, then repairs cross-cell outline
    ; boundaries for ordinary tagged C9/CA dialogue before replaying stock tail.
    ; Component 05 intro uses $9385 only for advances 3..8 and therefore skips.

org $ED7340
dialogue_chunk_commit:
    ; Non-line-break chunks keep the validated physical-cell conversion.
    ; Existing <=32-character line-break chunks keep their validated stock
    ; progression; newly possible 33-38-character line-break chunks are
    ; converted too so stock transfer never requests >32 physical cells.

org $ED7380
dialogue_chunk_cells_snapshot:
    ; When X equals the decoded count saved at renderer entry, convert the
    ; useful cursor to ceil(px/8). The helper is called again at final commit
    ; for a full 38-slot chunk and maps an exact 256-pixel cursor wrap to 32
    ; physical cells.

org $ED73B0
dialogue_event_render_scope:
    ; Return C=1 iff $9385 is non-zero; internal hooks use this private
    ; tag instead of re-testing shared global state.

org $ED7500
dialogue_parser_fetch:
    ; Generated by build_patch.py. Before source consumption, mode 2 computes
    ; the true remaining physical pixel budget, preflights direct/DTE glyphs,
    ; and ends the chunk before visible ink would clip. A safe source-space
    ; checkpoint is preferred when available; dynamic temporary sources are
    ; never rewound and DTE tokens remain atomic.

org $ED7700
dialogue_wrap_glyph_fit:
    ; Generated single-glyph visible-right-edge + advance test.

org $ED7780
dialogue_framed_right_edges:
    ; 128 generated framed rightmost-ink columns ($FF = blank glyph).
