; Secret of Mana (USA) — dialogue VWF continuous-cursor renderer
; =====================================================
;
; Runtime-validated architecture:
;   keep stock $C0:168A-$16B0 code -> glyph lookup/render path intact.
;
; Runtime-validated $C9-only checkpoint:
;   128-entry advance table at $ED:7200 (lookup runtime-validated)
;   space=$80 => 4 px advance
;   lowercase a-z => framed ink width + 1 px black separator
;     a-h/k/m-q/s/u-z = 7 px; i/l = 3 px; j = 4 px; r = 6 px; t = 5 px
;   uppercase A-Z runtime-validated => framed ink width + 1 (A-H/J-Z=7, I=3)
;   other non-lowercase glyphs => conservative min(8, rightmost ink column + 2)
;   complete lowercase framing via selector at $ED:71B0 (runtime-validated)
;   handled punctuation is runtime-validated with one black pixel on the LEFT
;   and one on the right of the ink
;   $BF-$C2: no shift; $C3/$C4: 0/1 px; $C6/$C7/$C9/$CA: no shift
;   $C8/$CB/$CC (!/(/)): 2/2/1 px; punctuation metrics include both gaps
;   $C5 colon runtime-validated: shift 1 px, advance 7 px => 2 px left / 3 px right; $CD untouched
;   French $D4-$E3 runtime-validated: shift 1 px / advance 7; $E4/$E5 (Œ/œ): shift 0 / advance 8
;   lowercase ink_width+1 metrics (runtime-validated)
;   post-stock-outline boundary repair at $ED:7280 (runtime-validated)
;     a-h/k/m-s/u-z = 1 px; i/l = 3 px; j/t = 2 px
;
; The lowercase metric batch changes only the table at $ED:7200; framing,
; compositor and hooks remain byte-identical to the validated checkpoint.
;
; The table lookup keeps A in 8-bit mode. It zero-extends the 7-bit glyph
; index through private WRAM $938A-$938B before loading 16-bit X.
;
; Continuous-cursor rule: every glyph starts at the true cumulative pixel
; cursor. No diagnostic tile-boundary realignment remains. This tests whether
; the stock-selected glyph rows can be composed continuously across shared
; cells for an entire dialogue line.
;
; NOTE: the non-$C9 branch in the generated helper must target the beginning
; of the stock `LDA $A1A4,X / INX` replay. A rejected build used a stale branch
; displacement after shortening the helper and corrupted GAME SELECT.
;
; $C0:16A4 intercepts only the already-selected stock font row. The helper
; composes that row at pixel_cursor&7, ORs the left part with any prior spill,
; writes the right spill to the next 12-byte tile cell, then returns the left
; byte for the original STA $9000,Y.
;
; The full $9000-$917F bitmap is cleared before a $C9 render because VWF
; composition no longer overwrites every stock cell independently.

hirom

org $C01168
    jml dialogue_outline_post

org $C013A3
    jml dialogue_progression_hook
    nop #2

org $C0167D
    jml dialogue_render_init

org $C01686
    jml dialogue_char_start

org $C016A4
    jsl dialogue_font_row

org $C016B1
    jml dialogue_char_end
    nop #2

org $ED7010
dialogue_progression_hook:
    inc $A181
    inc $A1D0
    jml $C013A9

org $ED7040
dialogue_render_init:
    ; Generated byte-exactly by build_patch.py.

org $ED7180
dialogue_char_start:
    ; For $C9, Y = floor(pixel_cursor/8)*12 from the true cumulative cursor,
    ; then replay the stock character load and continue into the untouched
    ; glyph-addressing path at $C0:168A.

org $ED70C0
dialogue_char_end:
    ; Read the current character's advance from the 128-entry table at
    ; $ED:7200, then reproduce the stock DEC $A176 / loop-or-return contract.
    ; A remains 8-bit throughout the lookup.

org $ED7100
dialogue_font_row:
    ; Replays LDA.l $D2DC00,X. Framing is still applied at this validated
    ; point; only the lowercase range decision is factored to $ED:71B0.

org $ED71B0
dialogue_framing_selector:
    ; a-h/k/m-s/u-z = 1 px, i/l = 3 px, j/t = 2 px.
    ; Rows after z branch to the adjacent punctuation selector.
    ; No generic shift table and no new WRAM state.

org $ED71E8
dialogue_punctuation_framing_selector:
    ; Post-lowercase dispatch. The fixed JML trampoline remains exactly at
    ; $ED:71F4 and forwards A+ to the extended selector.

org $ED72F0
dialogue_punctuation_framing_batch2_selector:
    ; A-H/J-Z shift 1 px, I shifts 3 px (runtime-validated).
    ; $B5-$BE digits stay generic/stock. Runtime-validated punctuation is
    ; preserved; $CD-$D3 stay untouched. French runtime-validated: $D4-$E3 shift
    ; 1 px, while full-width $E4/$E5 remain unshifted.


; ---------------------------------------------------------------------------
; Runtime-validated repair for outline pixels lost at 8-pixel cell boundaries
; ---------------------------------------------------------------------------

org $ED7280
dialogue_outline_post:
    ; Generated byte-exactly by build_patch.py. Entry is $C0:1168, after the
    ; stock JSR $162C has completed. The rejected $C0:1165 probe skipped that
    ; JSR and therefore suppressed most of the normal black outline.
