; Shared VWF runtime framing selector
; ===================================
; Readable 65816 reference for the code generated by vwf_framing.py.
; build_patch.py / vwf_framing.py are the executable canonical sources.
;
; Input (8-bit A, 16-bit X):
;   A = stock 8-pixel glyph row
;   X = 12-byte stock-font row offset from $D2:DC00
; Output:
;   A = row shifted left according to the validated framing policy
; X and accumulator width are preserved.
;
; Components 05 and 06 install/call this same contiguous C7 runtime copy.
; Component 06 no longer carries duplicate selector payloads in bank ED.

hirom

org $C744C0
vwf_framing_selector:
    cpx #$000C                 ; before lowercase a
    bcc .done
    cpx #$0144                 ; after lowercase z
    bcs vwf_punctuation_selector

    cpx #$006C                 ; i
    bcc .shift_one             ; a-h
    cpx #$0078                 ; j
    bcc .shift_three           ; i
    cpx #$0084                 ; k
    bcc .shift_two             ; j
    cpx #$0090                 ; l
    bcc .shift_one             ; k
    cpx #$009C                 ; m
    bcc .shift_three           ; l
    cpx #$00F0                 ; t
    bcc .shift_one             ; m-s
    cpx #$00FC                 ; u
    bcc .shift_two             ; t

.shift_one:
    asl
    bra .done
.shift_two:
    asl
    asl
    bra .done
.shift_three:
    asl
    asl
    asl
.done:
    rtl

; Exactly adjacent to the 56-byte lowercase selector above.
org $C744F8
vwf_punctuation_selector:
    cpx #$0144                 ; before uppercase A
    bcc .done
    bra .batch2
.done:
    rtl
    nop #4
.batch2:
    jml vwf_extended_framing_selector

org $C74508
vwf_extended_framing_selector:
    cpx #$01A4                 ; I
    bcc .shift_one             ; A-H
    cpx #$01B0                 ; J
    bcc .shift_three           ; I
    cpx #$027C                 ; after Z
    bcc .shift_one             ; J-Z

    cpx #$02F4                 ; $BF
    bcc .done                  ; $B5-$BE unchanged
    cpx #$0330                 ; $C4
    bcc .done                  ; $BF-$C3 unchanged
    cpx #$033C                 ; $C5
    bcc .shift_one             ; C4
    cpx #$0348                 ; $C6
    bcc .shift_one             ; C5
    cpx #$0360                 ; $C8
    bcc .done                  ; C6-C7
    cpx #$036C                 ; $C9
    bcc .shift_two             ; C8
    cpx #$0384                 ; $CB
    bcc .done                  ; C9-CA
    cpx #$0390                 ; $CC
    bcc .shift_two             ; CB
    cpx #$039C                 ; $CD
    bcc .shift_one             ; CC
    cpx #$03F0                 ; $D4
    bcc .done                  ; CD-D3 unchanged
    cpx #$04B0                 ; $E4
    bcc .shift_one             ; D4-E3

.done:
    rtl
.shift_one:
    asl
    rtl
.shift_two:
    asl
    asl
    rtl
.shift_three:
    asl
    asl
    asl
    rtl
