; Shared VWF 8x12 row compositor
; =============================
; Readable reference for the byte-identical helper generated by
; shared/vwf_compositor.py. The Python file is the executable canonical source.
;
; Components 05 and 06 each install these same bytes at $C7:4C90 so standalone
; operation is preserved and aggregate builds see an identical overlap.
;
; Entry contract (8-bit A):
;   A      = already-selected / already-framed 8-pixel source row
;   Y      = destination row offset in tile-major $7E:9000
;   $9382  = cumulative VWF pixel cursor
; Return:
;   A      = current-cell half ORed with existing $9000,Y
;   $900C,Y receives any right-side spill
;   X/Y and hidden accumulator B are preserved

hirom

!PIXEL_CURSOR = $9382
!BIT_SHIFT    = $9383
!SHIFT_COUNT  = $9384
!SOURCE_ROW   = $9388
!CURRENT_ROW  = $9389

org $C74C90
shared_vwf_row_compositor:
    sta !SOURCE_ROW
    lda !PIXEL_CURSOR
    and #$07
    sta !BIT_SHIFT
    beq .aligned

    ; current = source >> shift
    sta !SHIFT_COUNT
    lda !SOURCE_ROW
.right_loop:
    lsr
    dec !SHIFT_COUNT
    bne .right_loop
    ora $9000,y
    sta !CURRENT_ROW

    ; spill = source << (8-shift)
    lda #$08
    sec
    sbc !BIT_SHIFT
    sta !SHIFT_COUNT
    lda !SOURCE_ROW
.left_loop:
    asl
    dec !SHIFT_COUNT
    bne .left_loop
    ora $900C,y
    sta $900C,y

    lda !CURRENT_ROW
    rtl

.aligned:
    lda !SOURCE_ROW
    rtl
