; Shared stock-font VWF row renderer generated by shared/vwf_row_renderer.py.
; The Python module is the executable source of truth.
;
; Entry (8-bit A):
;   X = stock-font row offset (glyph_index * 12 + row)
;   Y = destination row offset in $7E:9000
;   $7E:9382 = cumulative pixel cursor
;
; Exit:
;   A = current-cell half, already merged with $9000,Y
;   X/Y preserved; hidden B byte untouched
;
; Installed byte-identically by components 05 and 06 at $C7:4560.

org $C74560
shared_vwf_stock_row:
    lda.l $D2DC00,x
    jsl $C744C0        ; shared framing selector
    jsl $C74C90        ; shared shift / merge / spill compositor
    rtl
