; Secret of Mana (USA) - New-game intro VWF
; ============================================
; Reference for the 65816 code emitted by build_patch.py.
; Dynamic event/DTE data is generated by the Python builder.
;
; Current layout:
;   event $0400 range : $CA:0C02 .. $CA:0E8B
;   private text buf  : $7E:9390-$93BB (44 bytes)
;   logical capacity  : 38 visible glyphs + one following control unit
;   VWF bitmap        : stock $7E:9000 tile-major 32 x 12-byte cells
;
; Hooks fall back to stock behavior outside event $0400.

lorom

!INTRO_START       = $0C02
!INTRO_END         = $0E8B      ; current checkpoint; generated dynamically
!PRIVATE_BUFFER    = $9390
!PRIVATE_BUF_SIZE  = $002C      ; 44 bytes
!STOCK_BUFFER      = $A1A4
!VWF_BITMAP        = $9000

!WIDTH_TABLE       = $C74440
!GLYPH_TABLE       = $C744C0
!CUSTOM_DTE        = $C74D00
!STOCK_DTE         = $C77299

; Scratch WRAM
!COUNT              = $9380
!LINE_END_FLAG      = $9381
!PIXEL_CURSOR       = $9382
!BIT_SHIFT          = $9383
!ROWS_LEFT          = $9384
!GLYPH_ADVANCE      = $9385
!TEMP16             = $9386
!SHIFTED_ROW        = $9388

; ---------------------------------------------------------------------------
; Stock hooks
; ---------------------------------------------------------------------------

org $C01664
    jml vwf_entry

org $C017CE
    jml parser_private_write

org $C016B8
    jml private_buffer_init

org $C018DE
    jml previous_char_read

org $C016C6
    jsl intro_capacity
    nop #6

org $C01719
    jsl intro_dte_load

; Stock direct/DTE boundary is moved from $D3 to $E6 so $D4-$E5 are direct
; glyph codes reserved for French characters.
org $C016F6
    db $E6

; Do not consume previous-row carry in the outline shift.
org $C0163D
    asl

; ---------------------------------------------------------------------------
; Intro-only VWF renderer
; ---------------------------------------------------------------------------

org $C74285

vwf_entry:
    lda.l $001D03
    cmp #$CA
    beq .check_pointer

.stock:
    lda $A1CE
    and #$7F
    jml $C01669

.check_pointer:
    rep #$20
    lda.l $001D01
    cmp #!INTRO_START
    bcc .stock16
    cmp #!INTRO_END
    bcs .stock16
    bra .intro

.stock16:
    sep #$20
    bra .stock

.intro:
    sep #$20

    ; Save decoded count and line-end flag.
    lda $A1CE
    and #$7F
    beq .stock
    sta !COUNT

    lda $A1CE
    and #$80
    sta !LINE_END_FLAG

    ; Clear the stock tile-major 32-cell x 12-row bitmap.
    ldx #$0000
.clear_bitmap:
    stz !VWF_BITMAP,x
    inx
    cpx #$0180
    bne .clear_bitmap

    stz !PIXEL_CURSOR
    ldx #$0000

.next_char:
    txa
    cmp !COUNT
    beq .done

    lda !PRIVATE_BUFFER,x
    inx
    phx

    ; Direct text codes are $80-based.
    rep #$20
    and #$00FF
    sec
    sbc #$0080
    tax
    sep #$20

    lda.l !WIDTH_TABLE,x
    sta !GLYPH_ADVANCE

    ; glyph_offset = glyph_index * 12
    rep #$20
    txa
    asl
    asl
    sta !TEMP16
    asl
    clc
    adc !TEMP16
    tax

    ; Compute destination cell and shift from the current pixel cursor.
    sep #$20
    lda !PIXEL_CURSOR
    and #$07
    sta !BIT_SHIFT

    rep #$20
    lda !PIXEL_CURSOR
    and #$00FF
    lsr
    lsr
    lsr
    asl
    asl
    sta !TEMP16
    asl
    clc
    adc !TEMP16
    tay

    sep #$20
    lda #$0C
    sta !ROWS_LEFT

.row:
    lda.l !GLYPH_TABLE,x
    inx
    rep #$20
    and #$00FF
    xba
    sta !SHIFTED_ROW
    phx

    sep #$20
    lda !BIT_SHIFT
    rep #$20
    and #$00FF
    tax
    lda !SHIFTED_ROW

.shift:
    cpx #$0000
    beq .shift_done
    lsr
    dex
    bra .shift

.shift_done:
    sta !SHIFTED_ROW
    sep #$20

    ; Right-side spill goes to the next 12-byte cell.
    lda !SHIFTED_ROW+1
    ora !VWF_BITMAP,y
    sta !VWF_BITMAP,y

    lda !SHIFTED_ROW
    ora !VWF_BITMAP+$0C,y
    sta !VWF_BITMAP+$0C,y

    plx
    iny
    dec !ROWS_LEFT
    bne .row

    plx
    lda !PIXEL_CURSOR
    clc
    adc !GLYPH_ADVANCE
    sta !PIXEL_CURSOR
    bra .next_char

.done:
    ; Stock event $0400 contains a WAIT in the middle of its final logical
    ; sentence. When the next opcode is WAIT, convert the VWF pixel cursor to
    ; an 8-pixel cell coordinate so resume-after-WAIT does not create a large
    ; fixed-width gap.
    rep #$20
    lda.l $001D01
    tax
    sep #$20
    lda.l $CA0000,x
    cmp #$28
    bne .return

    lda !PIXEL_CURSOR
    clc
    adc #$07
    lsr
    lsr
    lsr
    ora !LINE_END_FLAG
    sta $A1CE

.return:
    jml $C016B7

; ---------------------------------------------------------------------------
; Parser destination: private buffer during event $0400
; ---------------------------------------------------------------------------

org $C743D0

parser_private_write:
    pha

    lda.l $001D03
    cmp #$CA
    bne .stock8

    rep #$20
    lda.l $001D01
    cmp #!INTRO_START
    bcc .stock16
    cmp #!INTRO_END
    bcs .stock16

    sep #$20
    pla
    sta !PRIVATE_BUFFER,x
    inx
    jml $C017D2

.stock16:
    sep #$20
.stock8:
    pla
    sta !STOCK_BUFFER,x
    inx
    jml $C017D2

; ---------------------------------------------------------------------------
; Buffer initialization
; ---------------------------------------------------------------------------

org $C74AC0

private_buffer_init:
    lda.l $001D03
    cmp #$CA
    bne .stock

    rep #$20
    lda.l $001D01
    cmp #!INTRO_START
    bcc .stock16
    cmp #!INTRO_END
    bcs .stock16

    sep #$20
    ldx #$0000
    lda #$80
.private_loop:
    sta !PRIVATE_BUFFER,x
    inx
    cpx #!PRIVATE_BUF_SIZE
    bne .private_loop
    jml $C016C6

.stock16:
    sep #$20
.stock:
    ldx #$0000
    lda #$80
.stock_loop:
    sta !STOCK_BUFFER,x
    inx
    cpx #$0021
    bne .stock_loop
    jml $C016C6

; ---------------------------------------------------------------------------
; Previous-character read
; ---------------------------------------------------------------------------

org $C74B40

previous_char_read:
    sep #$20
    lda.l $001D03
    cmp #$CA
    bne .stock_from_8

    rep #$20
    lda.l $001D01
    cmp #!INTRO_START
    bcc .stock_from_16
    cmp #!INTRO_END
    bcs .stock_from_16

    lda.l $7E9390,x
    jml $C018E2

.stock_from_8:
    rep #$20
.stock_from_16:
    lda.l $7EA1A4,x
    jml $C018E2

; ---------------------------------------------------------------------------
; Intro logical capacity
; ---------------------------------------------------------------------------

org $C74BC0

intro_capacity:
    rep #$20
    lda.l $001D01
    cmp #!INTRO_START
    bcc .stock
    cmp #!INTRO_END
    bcs .stock

    sep #$20
    lda #$27              ; 39 parser units: 38 glyphs + following control
    sta $A1CA
    rtl

.stock:
    sep #$20
    lda $A16A
    sec
    sbc $A181
    sta $A1CA
    rtl

; ---------------------------------------------------------------------------
; Intro-private DTE table loader
; ---------------------------------------------------------------------------

org $C74C40

intro_dte_load:
    sep #$20
    lda.l $001D03
    cmp #$CA
    bne .stock8

    rep #$20
    lda.l $001D01
    cmp #!INTRO_START
    bcc .stock16
    cmp #!INTRO_END
    bcs .stock16

    ; X is the stock DTE table byte offset: (text_code - $C3) * 2.
    ; Rebase it so direct code $E6 maps to private pair index 0.
    txa
    sec
    sbc #(($E6-$C3)*2)
    tax
    lda.l !CUSTOM_DTE,x
    rtl

.stock8:
    rep #$20
.stock16:
    lda.l !STOCK_DTE,x
    rtl

; ---------------------------------------------------------------------------
; Generated data (emitted by build_patch.py)
; ---------------------------------------------------------------------------
;
; $C7:4440  128-byte glyph advance table
; $C7:44C0  128 x 12-byte left-compacted 8x12 font
; $C7:4D00  private intro DTE pair table
;
; The French glyph bitmaps are injected into the stock 8x12 font address space
; before the compact VWF font is generated. Their editable source is:
;   assets/font/french_glyphs.png
;
; The translated event itself is rebuilt by Python from:
;   assets/text/scrtxt_fr.bin
;   assets/text/intro_layout.json
;
; Therefore those generated binary data blocks are intentionally not duplicated
; as static db/incbin data here.
