; Secret of Mana (USA) - French Name Entry PLAYER_NAME DTE routing
;
; Ordinary event parsing keeps the French overlay's legacy threshold ($E1 alone,
; raised by the root combiner when another legacy charset component requires
; it). The relocated Name Entry resource in bank $E4 and the temporary
; PLAYER_NAME source at $7E:A22F use $E8 so $D3=♪, $E6=° and $E7=; remain
; direct glyphs without reinterpreting normal event DTE bytes.
;
; Executable bytes are generated by shared/name_entry/dte.py.

hirom

!BASE_THRESHOLD = $C74C86

org $C016F5
    jml name_dte_router

org $C745F0
name_dte_router:
    pha
    phb
    pla
    cmp #$E4
    beq .extended_saved
    cmp #$7E
    bne .base_saved

    rep #$20
    tya
    cmp #$A230
    bcc .base16_saved
    cmp #$A23C
    bcs .base16_saved

    sep #$20
.extended_saved:
    pla
    cmp #$E8
    bcs .upper_dte
    jml $C016F9

.base16_saved:
    sep #$20
.base_saved:
    pla
    cmp.l !BASE_THRESHOLD
    bcs .upper_dte
    jml $C016F9

.upper_dte:
    jml $C0170D
